#!/usr/bin/env node
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import path from 'node:path';
import { resolveProjectRoot } from './paths.js';
import { loadConfig } from './config.js';
import { createServer } from './server.js';

/**
 * Validates that resultsDir stays confined within root, applying the same
 * path-confinement rule used everywhere else. Throws a clear error if
 * resultsDir escapes the project root (e.g. via "../../somewhere" in a
 * committed sherpa.config.json) instead of silently writing outside the
 * project.
 *
 * Unlike resolveWithinRoot, this check is purely lexical (path.resolve/
 * path.relative on the strings, no fs.realpathSync). That's deliberate:
 * SHERPA_RESULTS_DIR is validated at startup, before any tool has run and
 * created the directory tree (which happens via
 * mkdirSync(..., {recursive: true})), so requiring the path (or its
 * parent) to already exist on disk would be too strict — a nested
 * resultsDir like "nested/.sherpa" is legitimate even though "nested/"
 * doesn't exist yet. This check offers no symlink-escape protection, but
 * that's acceptable here: at config-validation time there's nothing yet
 * to symlink-escape, and once tools write inside resultsDir they do so
 * via path.join(root, resultsDir, <uuid>) with filenames generated by
 * crypto.randomUUID() (not user-controlled), so there's no relevant
 * symlink attack surface.
 */
export function validateResultsDir(root: string, resultsDir: string): void {
  const resolved = path.resolve(root, resultsDir);
  const rel = path.relative(root, resolved);
  if (rel.startsWith(`..${path.sep}`) || rel === '..' || path.isAbsolute(rel)) {
    throw new Error(
      `sherpa cannot start: SHERPA_RESULTS_DIR ("${resultsDir}") escapes the project root ` +
      `(${root}). It must resolve to a path inside the root.`
    );
  }
}

async function main(): Promise<void> {
  const root = resolveProjectRoot(process.cwd());
  const config = loadConfig(root);
  validateResultsDir(root, config.resultsDir);
  const server = createServer(root, config);
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
